import type { Mode, TaxonomyPathInput } from "../domain/taxonomy";
import {
  meaningForLazerLegacy,
  meaningForLazerNative,
  meaningForStableOnly,
  type RequiredLevel,
  type SkinKind,
  type SkinMeaning,
} from "../domain/skin-asset";

export type GroupStrategy =
  | "fixed"
  | "filename-stem"
  | "animation-family";

export type ClassificationRule = {
  id: string;
  componentId: string;
  requiredLevel: RequiredLevel;
  path: TaxonomyPathInput;
  patterns: string[];
  modes: Mode[];
  kind?: SkinKind;
  meaning: SkinMeaning;
  groupStrategy?: GroupStrategy;
};

function defineRules<T extends readonly ClassificationRule[]>(rules: T): T {
  return rules;
}

const optional = "optional" satisfies RequiredLevel;
const recommended = "recommended" satisfies RequiredLevel;

export const classificationRules = defineRules([
  {
    id: "config.skin-ini",
    componentId: "config.skin-ini",
    requiredLevel: "required",
    path: {
      scopeId: "configs",
      categoryId: "skin-ini",
      groupId: "skin-ini",
    },
    patterns: ["skin.ini"],
    modes: [],
    kind: "text",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "config.lazer-layouts",
    componentId: "config.lazer-layouts",
    requiredLevel: optional,
    path: {
      scopeId: "configs",
      categoryId: "lazer-layouts",
      groupId: "lazer-layouts",
    },
    patterns: ["*.json"],
    modes: [],
    kind: "text",
    meaning: meaningForLazerNative(false),
    groupStrategy: "filename-stem",
  },

  {
    id: "osu.cursor",
    componentId: "osu.cursor",
    requiredLevel: recommended,
    path: {
      scopeId: "std",
      categoryId: "cursor",
      groupId: "cursor",
    },
    patterns: [
      "cursor.png",
      "cursormiddle.png",
      "cursortrail.png",
      "cursor-smoke.png",
      "cursor-ripple.png",
      "cursors/*",
    ],
    modes: ["osu"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "interface.global",
    componentId: "interface.global",
    requiredLevel: recommended,
    path: {
      scopeId: "interface",
      categoryId: "global",
      groupId: "global",
    },
    patterns: ["welcome_text*", "star2*"],
    modes: ["osu"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "filename-stem",
  },
  {
    id: "interface.input-overlay",
    componentId: "interface.input-overlay",
    requiredLevel: recommended,
    path: {
      scopeId: "interface",
      categoryId: "input-overlay",
      groupId: "input-overlay",
    },
    patterns: ["inputoverlay-background*", "inputoverlay-key*"],
    modes: [],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "interface.health-display",
    componentId: "interface.health-display",
    requiredLevel: recommended,
    path: {
      scopeId: "interface",
      categoryId: "health-display",
      groupId: "health-display",
    },
    patterns: [
      "scorebar-bg*",
      "scorebar-colour*",
      "scorebar-marker*",
      "scorebar-ki*",
      "scorebar-kidanger*",
      "scorebar-kidanger2*",
    ],
    modes: [],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "interface.judgements",
    componentId: "interface.judgements",
    requiredLevel: recommended,
    path: {
      scopeId: "interface",
      categoryId: "judgements",
      groupId: "judgements",
    },
    patterns: ["hit0*", "hit50*", "hit100*", "hit300*"],
    modes: ["osu"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "interface.judgement-particles",
    componentId: "interface.judgement-particles",
    requiredLevel: recommended,
    path: {
      scopeId: "interface",
      categoryId: "particles",
      groupId: "particles",
    },
    patterns: ["particle50*", "particle100*", "particle300*"],
    modes: ["osu"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },

  {
    id: "font.score",
    componentId: "font.score",
    requiredLevel: recommended,
    path: {
      scopeId: "fonts",
      categoryId: "score",
      groupId: "score",
    },
    patterns: ["score-*"],
    modes: [],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "font.combo",
    componentId: "font.combo",
    requiredLevel: recommended,
    path: {
      scopeId: "fonts",
      categoryId: "combo",
      groupId: "combo",
    },
    patterns: ["combo-*"],
    modes: [],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "font.default-numbers",
    componentId: "font.default-numbers",
    requiredLevel: recommended,
    path: {
      scopeId: "fonts",
      categoryId: "default-numbers",
      groupId: "default-numbers",
    },
    patterns: ["default-*"],
    modes: ["osu"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "font.score-entry",
    componentId: "font.score-entry",
    requiredLevel: optional,
    path: {
      scopeId: "fonts",
      categoryId: "score-entry",
      groupId: "score-entry",
    },
    patterns: ["scoreentry-*"],
    modes: [],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },

  {
    id: "osu.hit-circles",
    componentId: "osu.hit-circles",
    requiredLevel: recommended,
    path: {
      scopeId: "std",
      categoryId: "hit-circles",
      groupId: "hit-circles",
    },
    patterns: ["approachcircle*", "hitcircle*", "hitcircleoverlay*", "followpoint*"],
    modes: ["osu"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "filename-stem",
  },
  {
    id: "osu.slider",
    componentId: "osu.slider",
    requiredLevel: recommended,
    path: {
      scopeId: "std",
      categoryId: "slider",
      groupId: "slider",
    },
    patterns: [
      "sliderendcircle*",
      "sliderendcircleoverlay*",
      "sliderfollowcircle*",
      "sliderb*",
      "sliderb-nd*",
      "sliderb-spec*",
      "sliderscorepoint*",
      "reversearrow*",
      "sliderpoint10*",
      "sliderpoint30*",
    ],
    modes: ["osu"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "filename-stem",
  },
  {
    id: "osu.slider-miss-indicators",
    componentId: "osu.slider.miss-indicators",
    requiredLevel: recommended,
    path: {
      scopeId: "std",
      categoryId: "slider",
      groupId: "slider-miss-indicators",
    },
    patterns: ["sliderendmiss*", "slidertickmiss*"],
    modes: ["osu"],
    kind: "image",
    meaning: meaningForLazerLegacy(false),
    groupStrategy: "fixed",
  },
  {
    id: "osu.particles",
    componentId: "osu.particles",
    requiredLevel: recommended,
    path: {
      scopeId: "std",
      categoryId: "particles",
      groupId: "lighting",
    },
    patterns: ["lighting*"],
    modes: ["osu", "taiko", "catch"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "osu.spinner",
    componentId: "osu.spinner",
    requiredLevel: recommended,
    path: {
      scopeId: "std",
      categoryId: "spinner",
      groupId: "spinner",
    },
    patterns: [
      "spinner-rpm*",
      "spinner-clear*",
      "spinner-spin*",
      "spinner-background*",
      "spinner-metre*",
      "spinner-osu*",
      "spinner-glow*",
      "spinner-bottom*",
      "spinner-top*",
      "spinner-middle*",
      "spinner-middle2*",
    ],
    modes: ["osu"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "filename-stem",
  },
  {
    id: "osu.intro.skip-button",
    componentId: "osu.intro.skip-button",
    requiredLevel: optional,
    path: {
      scopeId: "std",
      categoryId: "intro",
      groupId: "skip-button",
    },
    patterns: ["play-skip*"],
    modes: ["osu"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },

  {
    id: "taiko.hit-bursts",
    componentId: "taiko.hit-bursts",
    requiredLevel: recommended,
    path: {
      scopeId: "taiko",
      categoryId: "hit-bursts",
      groupId: "hit-bursts",
    },
    patterns: [
      "taiko-hit0*",
      "taiko-hit100*",
      "taiko-hit100k*",
      "taiko-hit300*",
      "taiko-hit300k*",
    ],
    modes: ["taiko"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "taiko.notes",
    componentId: "taiko.notes",
    requiredLevel: recommended,
    path: {
      scopeId: "taiko",
      categoryId: "notes",
      groupId: "notes",
    },
    patterns: ["taikohitcircle*", "taikobigcircle*"],
    modes: ["taiko"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "filename-stem",
  },
  {
    id: "taiko.playfield-upper",
    componentId: "taiko.playfield.upper",
    requiredLevel: recommended,
    path: {
      scopeId: "taiko",
      categoryId: "playfield-upper",
      groupId: "scroller",
    },
    patterns: ["taiko-slider.png", "taiko-slider-fail.png", "taiko-glow.png"],
    modes: ["taiko"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "filename-stem",
  },
  {
    id: "taiko.playfield-lower",
    componentId: "taiko.playfield.lower",
    requiredLevel: recommended,
    path: {
      scopeId: "taiko",
      categoryId: "playfield-lower",
      groupId: "playfield",
    },
    patterns: [
      "taiko-bar-left*",
      "taiko-drum-inner*",
      "taiko-drum-outer*",
      "taiko-bar-right*",
      "taiko-bar-right-glow*",
      "taiko-barline*",
    ],
    modes: ["taiko"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "filename-stem",
  },
  {
    id: "taiko.drumrolls",
    componentId: "taiko.drumrolls",
    requiredLevel: recommended,
    path: {
      scopeId: "taiko",
      categoryId: "drumrolls",
      groupId: "drumrolls",
    },
    patterns: ["taiko-roll-middle*", "taiko-roll-end*"],
    modes: ["taiko"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "taiko.shaker",
    componentId: "taiko.shaker",
    requiredLevel: recommended,
    path: {
      scopeId: "taiko",
      categoryId: "shaker",
      groupId: "shaker",
    },
    patterns: ["spinner-warning*", "spinner-circle*", "spinner-approachcircle*"],
    modes: ["taiko"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },

  {
    id: "catch.catcher",
    componentId: "catch.catcher",
    requiredLevel: recommended,
    path: {
      scopeId: "catch",
      categoryId: "catcher",
      groupId: "catcher",
    },
    patterns: ["fruit-catcher-*", "fruit-ryuuta*"],
    modes: ["catch"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "filename-stem",
  },
  {
    id: "catch.fruits",
    componentId: "catch.fruits",
    requiredLevel: recommended,
    path: {
      scopeId: "catch",
      categoryId: "fruits",
      groupId: "fruits",
    },
    patterns: [
      "fruit-pear*",
      "fruit-grapes*",
      "fruit-apple*",
      "fruit-orange*",
      "fruit-bananas*",
      "fruit-drop*",
      "fruit-droplet*",
    ],
    modes: ["catch"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "filename-stem",
  },

  {
    id: "mania.hit-bursts",
    componentId: "mania.hit-bursts",
    requiredLevel: recommended,
    path: {
      scopeId: "mania",
      categoryId: "hit-bursts",
      groupId: "hit-bursts",
    },
    patterns: [
      "mania-hit0*",
      "mania-hit50*",
      "mania-hit100*",
      "mania-hit200*",
      "mania-hit300*",
      "mania-hit300g*",
    ],
    modes: ["mania"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "mania.comboburst",
    componentId: "mania.comboburst",
    requiredLevel: optional,
    path: {
      scopeId: "mania",
      categoryId: "comboburst",
      groupId: "comboburst",
    },
    patterns: ["comboburst-mania*"],
    modes: ["mania"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "mania.keys",
    componentId: "mania.keys",
    requiredLevel: recommended,
    path: {
      scopeId: "mania",
      categoryId: "keys",
      groupId: "keys",
    },
    patterns: ["mania-key*"],
    modes: ["mania"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "mania.notes",
    componentId: "mania.notes",
    requiredLevel: recommended,
    path: {
      scopeId: "mania",
      categoryId: "notes",
      groupId: "notes",
    },
    patterns: ["mania-note*"],
    modes: ["mania"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "mania.stage",
    componentId: "mania.stage",
    requiredLevel: recommended,
    path: {
      scopeId: "mania",
      categoryId: "stage",
      groupId: "stage",
    },
    patterns: ["mania-stage*", "mania-warningarrow*"],
    modes: ["mania"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "filename-stem",
  },
  {
    id: "mania.lighting",
    componentId: "mania.lighting",
    requiredLevel: recommended,
    path: {
      scopeId: "mania",
      categoryId: "lighting",
      groupId: "lighting",
    },
    patterns: ["mania-light*", "lightingg*", "lightingl*", "lightingn*"],
    modes: ["mania"],
    kind: "image",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },

  {
    id: "sound.hitsounds",
    componentId: "sound.hitsounds",
    requiredLevel: recommended,
    path: {
      scopeId: "sounds",
      categoryId: "hitsounds",
      groupId: "hitsounds",
    },
    patterns: [
      "normal-hitnormal.*",
      "normal-hitwhistle.*",
      "normal-hitfinish.*",
      "normal-hitclap.*",
      "soft-hitnormal.*",
      "soft-hitwhistle.*",
      "soft-hitfinish.*",
      "soft-hitclap.*",
      "drum-hitnormal.*",
      "drum-hitwhistle.*",
      "drum-hitfinish.*",
      "drum-hitclap.*",
    ],
    modes: ["osu", "taiko", "catch"],
    kind: "audio",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "sound.slider",
    componentId: "sound.slider",
    requiredLevel: recommended,
    path: {
      scopeId: "sounds",
      categoryId: "slider",
      groupId: "slider",
    },
    patterns: [
      "normal-slidertick.*",
      "normal-sliderslide.*",
      "normal-sliderwhistle.*",
      "soft-slidertick.*",
      "soft-sliderslide.*",
      "soft-sliderwhistle.*",
      "drum-slidertick.*",
      "drum-sliderslide.*",
      "drum-sliderwhistle.*",
    ],
    modes: ["osu"],
    kind: "audio",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "sound.gameplay",
    componentId: "sound.gameplay",
    requiredLevel: recommended,
    path: {
      scopeId: "sounds",
      categoryId: "gameplay",
      groupId: "gameplay",
    },
    patterns: [
      "spinnerspin.*",
      "spinnerbonus.*",
      "spinnerbonus-max.*",
      "combobreak.*",
      "failsound.*",
      "sectionpass.*",
      "sectionfail.*",
    ],
    modes: ["osu", "taiko", "catch", "mania"],
    kind: "audio",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "sound.countdown",
    componentId: "sound.countdown",
    requiredLevel: optional,
    path: {
      scopeId: "sounds",
      categoryId: "countdown",
      groupId: "countdown",
    },
    patterns: ["count.*", "count1s.*", "count2s.*", "count3s.*", "gos.*", "readys.*"],
    modes: ["osu", "taiko", "catch", "mania"],
    kind: "audio",
    meaning: meaningForLazerLegacy(true),
    groupStrategy: "fixed",
  },
  {
    id: "sound.lazer",
    componentId: "sound.lazer",
    requiredLevel: optional,
    path: {
      scopeId: "sounds",
      categoryId: "lazer",
      groupId: "lazer",
    },
    patterns: [
      "fountain-loop.*",
      "fountain-shoot.*",
      "taiko-strong-hitnormal.*",
      "taiko-strong-hitclap.*",
      "taiko-strong-hitflourish.*",
      "rank-up.*",
      "rank-down.*",
      "applause-s.*",
      "applause-a.*",
      "applause-b.*",
      "applause-c.*",
      "applause-d.*",
    ],
    modes: ["osu", "taiko", "catch", "mania"],
    kind: "audio",
    meaning: meaningForLazerLegacy(false),
    groupStrategy: "filename-stem",
  },

  {
    id: "font.raw-files",
    componentId: "font.raw-files",
    requiredLevel: optional,
    path: {
      scopeId: "fonts",
      categoryId: "font-files",
      groupId: "font-files",
    },
    patterns: ["*.ttf", "*.otf", "*.fnt"],
    modes: [],
    kind: "font",
    meaning: {
      lazerLegacy: false,
      lazerNative: false,
      stable: false,
    },
    groupStrategy: "fixed",
  },

  {
    id: "stable.ranking",
    componentId: "stable.ranking",
    requiredLevel: optional,
    path: {
      scopeId: "stable",
      categoryId: "ranking",
      groupId: "ranking",
    },
    patterns: ["ranking-*"],
    modes: [],
    kind: "image",
    meaning: meaningForStableOnly(),
    groupStrategy: "filename-stem",
  },
  {
    id: "stable.classic-menu",
    componentId: "stable.classic-menu",
    requiredLevel: optional,
    path: {
      scopeId: "stable",
      categoryId: "classic-menu",
      groupId: "classic-menu",
    },
    patterns: [
      "button-*",
      "menu-back*",
      "menu-background*",
      "menu-snow*",
      "options-offset-tick*",
    ],
    modes: [],
    kind: "image",
    meaning: meaningForStableOnly(),
    groupStrategy: "filename-stem",
  },
  {
    id: "stable.songselect",
    componentId: "stable.songselect",
    requiredLevel: optional,
    path: {
      scopeId: "stable",
      categoryId: "songselect",
      groupId: "songselect",
    },
    patterns: [
      "songselect-*",
      "menu-button-background*",
      "rank-forum*",
      "star.png",
    ],
    modes: [],
    kind: "image",
    meaning: meaningForStableOnly(),
    groupStrategy: "filename-stem",
  },
  {
    id: "stable.mode-icons",
    componentId: "stable.mode-icons",
    requiredLevel: optional,
    path: {
      scopeId: "stable",
      categoryId: "mode-icons",
      groupId: "mode-icons",
    },
    patterns: ["mode-osu*", "mode-taiko*", "mode-fruits*", "mode-mania*"],
    modes: [],
    kind: "image",
    meaning: meaningForStableOnly(),
    groupStrategy: "fixed",
  },
  {
    id: "stable.mod-icons",
    componentId: "stable.mod-icons",
    requiredLevel: optional,
    path: {
      scopeId: "stable",
      categoryId: "mod-icons",
      groupId: "mod-icons",
    },
    patterns: ["selection-mod-*"],
    modes: [],
    kind: "image",
    meaning: meaningForStableOnly(),
    groupStrategy: "fixed",
  },
  {
    id: "stable.selection",
    componentId: "stable.selection",
    requiredLevel: optional,
    path: {
      scopeId: "stable",
      categoryId: "selection",
      groupId: "selection",
    },
    patterns: [
      "selection-mode*",
      "selection-mods*",
      "selection-random*",
      "selection-options*",
      "selection-tab*",
    ],
    modes: [],
    kind: "image",
    meaning: meaningForStableOnly(),
    groupStrategy: "fixed",
  },
  {
    id: "stable.pause-fail",
    componentId: "stable.pause-fail",
    requiredLevel: optional,
    path: {
      scopeId: "stable",
      categoryId: "pause-fail",
      groupId: "pause-fail",
    },
    patterns: ["pause-*", "fail-background*"],
    modes: [],
    kind: "image",
    meaning: meaningForStableOnly(),
    groupStrategy: "filename-stem",
  },
  {
    id: "stable.break-editor",
    componentId: "stable.break-editor",
    requiredLevel: optional,
    path: {
      scopeId: "stable",
      categoryId: "break-editor",
      groupId: "break-editor",
    },
    patterns: [
      "section-pass*",
      "section-fail*",
      "play-warningarrow*",
      "arrow-*",
      "play-unranked*",
      "multi-skipped*",
      "masking-border*",
      "hitcircleselect*",
    ],
    modes: [],
    kind: "image",
    meaning: meaningForStableOnly(),
    groupStrategy: "filename-stem",
  },
  {
    id: "stable.countdown-images",
    componentId: "stable.countdown-images",
    requiredLevel: optional,
    path: {
      scopeId: "stable",
      categoryId: "countdown-images",
      groupId: "countdown-images",
    },
    patterns: ["count1.png", "count2.png", "count3.png", "go.png", "ready.png"],
    modes: [],
    kind: "image",
    meaning: meaningForStableOnly(),
    groupStrategy: "fixed",
  },
  {
    id: "stable.decorative",
    componentId: "stable.decorative",
    requiredLevel: optional,
    path: {
      scopeId: "stable",
      categoryId: "decorative",
      groupId: "decorative",
    },
    patterns: ["comboburst*", "taiko-flower-group*", "taiko-hit300g*", "pippidon*"],
    modes: [],
    kind: "image",
    meaning: meaningForStableOnly(),
    groupStrategy: "filename-stem",
  },
  {
    id: "stable.classic-ui-sounds",
    componentId: "stable.classic-ui-sounds",
    requiredLevel: optional,
    path: {
      scopeId: "stable",
      categoryId: "classic-ui-sounds",
      groupId: "classic-ui-sounds",
    },
    patterns: [
      "applause.*",
      "pause-loop.*",
      "comboburst*.*",
      "sliderbar.*",
      "whoosh.*",
      "back-button-hover.*",
      "click-short.*",
      "menuclick.*",
      "menu-*-hover.*",
      "pause-hover.*",
      "pause-*-hover.*",
      "key-*.*",
      "heartbeat.*",
      "seeya.*",
      "welcome.*",
      "metronomelow.*",
      "match-*.*",
    ],
    modes: [],
    kind: "audio",
    meaning: meaningForStableOnly(),
    groupStrategy: "filename-stem",
  },
] as const);

export function classificationRuleId(rule: ClassificationRule): string {
  return rule.id;
}