export {
  buildGraph,
  computeGraphStatus,
  graphBlame,
  graphFilePath,
  graphImpact,
  isGraphStale,
  readGraph,
  scanProject,
  writeGraph,
  type GraphSnapshot,
  type GraphStatus,
  type ScanResult,
} from './core/graph'
export {
  buildContextPlan,
  buildGraphContextPlan,
  computePermissionEnvelope,
  normalizeContextMode,
  type ContextMode,
  type ContextPlan,
  type ContextPlanOptions,
  type SelectorV2PlanOptions,
} from './core/context'
export { runDoctor, type DoctorOptions } from './core/doctor'
export { loadHarnessDocuments, strictnessForPath, extractMarkdownLinks, sha256Text, toPosixPath } from './core/docs'
export { parseFrontmatter, type ParsedFrontmatter } from './core/frontmatter'
export {
  generateGeneratedFiles,
  type GenerateOptions,
  type GenerateResult,
  type GeneratedFile,
  type GeneratedFileKind,
} from './core/generate'
export { handleGuiRequest, listGuiStaticFiles, type GuiResponse, type GuiRoute, type GuiServerOptions } from './core/gui'
export { compileIndexes, type GeneratedFileName, type IndexOptions, type IndexResult } from './core/indexer'
export {
  listKnowledgeProposals,
  promoteKnowledgeProposal,
  proposeKnowledge,
  rejectKnowledgeProposal,
  duplicateCandidatesWithSemantic,
  type KnowledgePromotionOptions,
  type KnowledgePromotionResult,
  type KnowledgeProposalOptions,
  type KnowledgeProposalResult,
  type KnowledgeProposalSummary,
  type KnowledgeRejectOptions,
  type KnowledgeRejectResult,
} from './core/knowledge'
export {
  buildContextRenderCommand,
  buildRunInitCommand,
  diagnosticMessageWithRecovery,
  inferRoleIds,
  listAtelierRegistryEntries,
  nextActionsForRunInit,
  recoveryLinesForDiagnostic,
  renderEntrypointProtocol,
  runPolicyForWorkflow,
  suggestSymbolicIds,
  type AtelierNextAction,
  type AtelierRegistryEntry,
  type AtelierRunPolicy,
} from './core/llm-protocol'
export { MCP_TOOL_NAMES, buildMcpServer, runMcpServer, type McpServerOptions } from './core/mcp'
export { listNxProjects, repoOwner, type NxProject, type RepoOwnerResult, type RepoOwnerSource } from './core/owner'
export {
  compilePathOwnership,
  compileRepoMap,
  lookupOwnership,
  type OwnershipHint,
  type PathOwnership,
  type PathOwnershipEntry,
  type RepoFile,
  type RepoFileKind,
  type RepoMap,
  type RepoProject,
} from './core/repo-map'
export {
  buildSemanticQuery,
  findDuplicateKnowledgeCandidates,
  runSemanticExpansion,
  type SemanticHit,
  type SemanticOptions,
  type SemanticQuery,
  type SemanticResult,
  type SemanticSource,
} from './core/semantic'
export {
  renameId,
  type IdRenameChange,
  type IdRenameChangeKind,
  type IdRenameOptions,
  type IdRenameResult,
} from './core/rename'
export {
  closeRun,
  expandRunContext,
  initRun,
  renderContextForOptions,
  runStatus,
  type ContextExpandOptions,
  type ContextExpandResult,
  type ContextRenderOptions,
  type ContextRenderResult,
  type RunCloseOptions,
  type RunCloseResult,
  type RunInitOptions,
  type RunInitResult,
  type RunStatusOptions,
  type RunStatusResult,
} from './core/runs'
export {
  appendEvent,
  buildContentHashIndex,
  classifyChange,
  classifyCuratedEdit,
  classifyDeletionIntent,
  classifyMissingControl,
  classifyOrphanSource,
  createEvent,
  createFileChangedEvent,
  createFileDeletedEvent,
  createFileMovedEvent,
  createReconciliationFindingEvent,
  createRunCompletedEvent,
  createRunStartedEvent,
  generateEventId,
  readEvents,
  type AtelierEvent,
  type EventKind,
} from './core/events'
export {
  buildCoverageReport,
  findMissingControls,
  listControls,
  observeControls,
  type ControlCoverageEntry,
  type ControlCoverageReport,
  type ControlMechanism,
  type ControlOwnershipMode,
  type ControlProvenance,
  type ControlType,
} from './core/controls'
export {
  checkPolicy,
  evaluateApproval,
  evaluateCommand,
  evaluatePath,
  evaluateTool,
  explainPolicy,
  loadPolicyConfig,
  simulatePolicy,
  type ApprovalPolicy,
  type CommandRule,
  type PathRule,
  type PolicyConfig,
  type PolicyDecision,
  type PolicyResult,
  type PermissionMode,
  type ToolRule,
} from './core/policy'
export {
  assignTask,
  closeTask,
  createRole,
  createTask,
  editRole,
  listTasks,
  splitTask,
  taskStatus,
  type RoleCreateOptions,
  type RoleEditOptions,
  type TaskArtifact,
  type TaskAssignOptions,
  type TaskCreateOptions,
  type TaskSplitOptions,
  type TaskStatus,
} from './core/tasks'
export {
  reconcile,
  repairDryRun,
  type ReconcilerOptions,
  type ReconcilerResult,
  type RepairDryRunResult,
} from './core/reconciler'
export type {
  Diagnostic,
  DiagnosticCode,
  DiagnosticSeverity,
  DoctorReport,
  DoctorSummary,
  HarnessDocument,
  HarnessFrontmatter,
  HarnessKind,
  HarnessStatus,
  MarkdownLink,
  Strictness,
  ArtifactKind,
  ArtifactStatus,
  EdgeKind,
  OwnershipMode,
  Artifact,
  Edge,
  RiskAction,
  ReconciliationFinding,
  SelectorV2Input,
  SelectorV2Trace,
  PermissionEnvelope,
} from './core/schema'
